{{- if not .Values.deployment.remote_cluster_resources_only }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kiali-server.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "kiali-server.labels" . | nindent 4 }}
spec:
{{- if not .Values.deployment.hpa.spec }}
  replicas: {{ .Values.deployment.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "kiali-server.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: {{ include "kiali-server.fullname" . }}
      labels:
        {{- include "kiali-server.labels" . | nindent 8 }}
        {{- if .Values.deployment.pod_labels }}
        {{- toYaml .Values.deployment.pod_labels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.server.observability.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.server.observability.metrics.port | quote }}
        {{- else }}
        prometheus.io/scrape: "false"
        prometheus.io/port: ""
        {{- end }}
        kiali.io/dashboards: go,kiali
        {{- if .Values.deployment.pod_annotations }}
        {{- toYaml .Values.deployment.pod_annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "kiali-server.fullname" . }}
      {{- if .Values.deployment.priority_class_name }}
      priorityClassName: {{ .Values.deployment.priority_class_name | quote }}
      {{- end }}
      {{- if .Values.deployment.image_pull_secrets }}
      imagePullSecrets:
      {{- range .Values.deployment.image_pull_secrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.deployment.host_aliases }}
      hostAliases:
      {{- toYaml .Values.deployment.host_aliases | nindent 6 }}
      {{- end }}
      {{- if .Values.deployment.dns }}
      {{- if .Values.deployment.dns.policy }}
      dnsPolicy: "{{ .Values.deployment.dns.policy }}"
      {{- end }}
      {{- if .Values.deployment.dns.config }}
      dnsConfig:
      {{- toYaml .Values.deployment.dns.config | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - image: "{{ .Values.deployment.image_name }}{{ if .Values.deployment.image_digest }}@{{ .Values.deployment.image_digest }}{{ end }}:{{ .Values.deployment.image_version }}"
        imagePullPolicy: {{ .Values.deployment.image_pull_policy | default "Always" }}
        name: {{ include "kiali-server.fullname" . }}
        command:
        - "/opt/kiali/kiali"
        - "-config"
        - "/kiali-configuration/config.yaml"
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
        {{- if .Values.deployment.security_context}}
        {{- toYaml .Values.deployment.security_context | nindent 10 }}
        {{- else }}
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        {{- end }}
        ports:
        - name: api-port
          containerPort: {{ .Values.server.port | default 20001 }}
        {{- if .Values.server.observability.metrics.enabled }}
        - name: http-metrics
          containerPort: {{ .Values.server.observability.metrics.port | default 9090 }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: {{ include "kiali-server.server.web_root" . | trimSuffix "/"  }}/healthz
            port: api-port
            {{- if (include "kiali-server.identity.cert_file" .) }}
            scheme: HTTPS
            {{- else }}
            scheme: HTTP
            {{- end }}
          initialDelaySeconds: {{ .Values.deployment.probes.readiness.initial_delay_seconds | int | default 5 }}
          periodSeconds: {{ .Values.deployment.probes.readiness.period_seconds | int | default 30 }}
        livenessProbe:
          httpGet:
            path: {{ include "kiali-server.server.web_root" . | trimSuffix "/"  }}/healthz
            port: api-port
            {{- if (include "kiali-server.identity.cert_file" .) }}
            scheme: HTTPS
            {{- else }}
            scheme: HTTP
            {{- end }}
          initialDelaySeconds: {{ .Values.deployment.probes.liveness.initial_delay_seconds | int | default 5 }}
          periodSeconds: {{ .Values.deployment.probes.liveness.period_seconds | int | default 30 }}
        startupProbe:
          httpGet:
            path: {{ include "kiali-server.server.web_root" . | trimSuffix "/"  }}/healthz
            port: api-port
            {{- if (include "kiali-server.identity.cert_file" .) }}
            scheme: HTTPS
            {{- else }}
            scheme: HTTP
            {{- end }}
          failureThreshold: {{ .Values.deployment.probes.startup.failure_threshold | int | default 6 }}
          initialDelaySeconds: {{ .Values.deployment.probes.startup.initial_delay_seconds | int | default 30 }}
          periodSeconds: {{ .Values.deployment.probes.startup.period_seconds | int | default 10 }}
        env:
        - name: ACTIVE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOG_LEVEL
          value: "{{ include "kiali-server.logLevel" . }}"
        - name: LOG_FORMAT
          value: "{{ .Values.deployment.logger.log_format }}"
        - name: LOG_TIME_FIELD_FORMAT
          value: "{{ .Values.deployment.logger.time_field_format }}"
        - name: LOG_SAMPLER_RATE
          value: "{{ .Values.deployment.logger.sampler_rate }}"
        {{- range .Values.deployment.custom_envs }}
        - name: {{ .name | quote }}
          value: {{ .value | quote }}
        {{- end }}
        volumeMounts:
        - name: {{ include "kiali-server.fullname" . }}-configuration
          mountPath: "/kiali-configuration"
        - name: {{ include "kiali-server.fullname" . }}-cert
          mountPath: "/kiali-cert"
        - name: {{ include "kiali-server.fullname" . }}-secret
          mountPath: "/kiali-secret"
        - name: {{ include "kiali-server.fullname" . }}-cabundle
          mountPath: "/kiali-cabundle"
        {{- range .Values.deployment.custom_secrets }}
        - name: {{ .name }}
          mountPath: "{{ .mount }}"
        {{- end }}
        - name: "kiali-multi-cluster-secret"
          mountPath: "/kiali-remote-cluster-secrets/kiali-multi-cluster-secret"
          readOnly: true
        {{- range $key, $val := (include "kiali-server.remote-cluster-secrets" .) | fromJson }}
        - name: {{ $key }}
          mountPath: "/kiali-remote-cluster-secrets/{{ $val }}"
          readOnly: true
        {{- end }}
        {{- range .Values.clustering.clusters }}
        {{- if and (.secret_name) (ne .secret_name "kiali-multi-cluster-secret") }}
        - name: {{ .name }}
          mountPath: "/kiali-remote-cluster-secrets/{{ .secret_name }}"
          readOnly: true
        {{- end }}
        {{- end }}
        {{- if .Values.deployment.resources }}
        resources:
        {{- toYaml .Values.deployment.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: {{ include "kiali-server.fullname" . }}-configuration
        configMap:
          name: {{ include "kiali-server.fullname" . }}
      - name: {{ include "kiali-server.fullname" . }}-cert
        secret:
          {{- if eq "true" (include "kiali-server.isOpenShift" .) }}
          secretName: {{ include "kiali-server.fullname" . }}-cert-secret
          {{- else }}
          secretName: istio.{{ include "kiali-server.fullname" . }}-service-account
          {{- end }}
          {{- if not (include "kiali-server.identity.cert_file" .) }}
          optional: true
          {{- end }}
      - name: {{ include "kiali-server.fullname" . }}-secret
        secret:
          secretName: {{ .Values.deployment.secret_name }}
          optional: true
      - name: {{ include "kiali-server.fullname" . }}-cabundle
        configMap:
          name: {{ include "kiali-server.fullname" . }}-cabundle
      {{- if not (eq "true" (include "kiali-server.isOpenShift" .)) }}
          optional: true
      {{- end }}
      {{- range .Values.deployment.custom_secrets }}
      - name: {{ .name }}
      {{- if .csi}}
        csi: {{ toYaml .csi | nindent 10 }}
      {{- else }}
        secret:
          secretName: {{ .name }}
          optional: {{ .optional | default false }}
      {{- end }}
      {{- end }}
      - name: "kiali-multi-cluster-secret"
        secret:
          secretName: "kiali-multi-cluster-secret"
          optional: true
      {{- range $key, $val := (include "kiali-server.remote-cluster-secrets" .) | fromJson }}
      - name: {{ $key }}
        secret:
          secretName: {{ $val }}
      {{- end }}
      {{- range .Values.clustering.clusters }}
      {{- if and (.secret_name) (ne .secret_name "kiali-multi-cluster-secret") }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secret_name }}
      {{- end }}
      {{- end }}
      {{- if or (.Values.deployment.affinity.node) (or (.Values.deployment.affinity.pod) (.Values.deployment.affinity.pod_anti)) }}
      affinity:
        {{- if .Values.deployment.affinity.node }}
        nodeAffinity:
        {{- toYaml .Values.deployment.affinity.node | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.affinity.pod }}
        podAffinity:
        {{- toYaml .Values.deployment.affinity.pod | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.affinity.pod_anti }}
        podAntiAffinity:
        {{- toYaml .Values.deployment.affinity.pod_anti | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
      {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.node_selector }}
      nodeSelector:
      {{- toYaml .Values.deployment.node_selector | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.topology_spread_constraints }}
      topologySpreadConstraints:
      {{- toYaml .Values.deployment.topology_spread_constraints | nindent 8 }}
      {{- end }}
...
{{- end }}
