testName: selector-operators
deployment:
  image_version: latest
  version_label: test
  probes:
    liveness:
      initial_delay_seconds: 1
      period_seconds: 1
    readiness:
      initial_delay_seconds: 1
      period_seconds: 1
    startup:
      failure_threshold: 10
      initial_delay_seconds: 1
      period_seconds: 1
  cluster_wide_access: false
  discovery_selectors:
    default:
    - matchExpressions:
      - key: env
        operator: NotIn
        values:
        - dev
      - key: team
        operator: Exists

